version: '3'
services:
  mysql:
    image: 'mysql:8.0.27'
    restart: 'no'
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - '../.data/mysql:/var/lib/mysql'
      - './mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_USER_PASSWORD}'
  nginx:
    image: 'lscr.io/linuxserver/nginx:latest'
    restart: 'no'
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - '../backend:/var/www/backend'
      - './nginx/http.conf:/config/nginx/site-confs/default.conf'
    ports:
      - '${NGINX_BACKEND_HTTP_PORT}:3080'
      - '${NGINX_BACKEND_HTTPS_PORT}:3443'
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build: phpfpm
    restart: 'no'
    volumes:
      - '../backend:/var/www/backend'
      - './phpfpm/php.ini:/usr/local/etc/php/conf.d/local.ini'
      - './phpfpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './phpfpm/crontab:/etc/cron.d/crontab'
      - './phpfpm/horizon.conf:/etc/supervisor/conf.d/horizon.conf'
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  redis:
    image: 'redis:alpine'
    restart: 'no'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    ports:
      - '${REDIS_PORT}:6379'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    environment:
      PMA_HOST: mysql
      PMA_PORT: '${MYSQL_PORT}'
      MAX_EXECUTION_TIME: 1800
      MEMORY_LIMIT: '4G'
      UPLOAD_LIMIT: '1G'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    links:
      - mysql
    depends_on:
      - mysql
  frontend:
    build:
      context: ../frontend
      dockerfile: '../.docker/frontend/Dockerfile'
    ports:
      - '3000:3000'
  python:
    container_name: python_app
    build:
      context: ../gpt_service
      dockerfile: '../.docker/python/Dockerfile'
    restart: 'no'
    volumes:
      - '../gpt_service:/var/www/python'
    ports:
      - "5005:5005"
    depends_on:
      - mysql